"""remove age from  students table

Revision ID: 82e6efab3519
Revises: 84355269a3b5
Create Date: 2026-08-28 08:28:53.936332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e6efab3519'
down_revision: Union[str, Sequence[str], None] = '84355269a3b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('age', sa.BIGINT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
