"""add city col to students table

Revision ID: 84355269a3b5
Revises: d1f80a952b84
Create Date: 2026-08-28 08:26:46.369337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84355269a3b5'
down_revision: Union[str, Sequence[str], None] = 'd1f80a952b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('city', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'city')
    # ### end Alembic commands ###
